my_streamlit_app/
│
├── Home.py               # Main page (first tab)
├── PathEditor.py         # Path Editor page
├── ExcelProcessor.py     # Excel Processor page
├── .streamlit/
│   └── config.toml       # Configuration for layout and tabs
└── requirements.txt      # (Optional) Python dependencies
